export enum ORDER_TYPE {
    LIMIT = 'LIMIT',
    MARKET = 'MARKET',
    STOP = 'STOP',
    STOP_LIMIT = 'STOP_LIMIT',
    ICEBERG = 'ICEBERG',
    NONE_MARKET_FETCH_LATEST_EXECUTION = 'NONE_MARKET_FETCH_LATEST_EXECUTION',
}